name: Build Gomi

on:
  release:
    types:
      - created
      
permissions:
  contents: write
  checks: write

  actions: read
  issues: read
  packages: write
  pull-requests: read
  repository-projects: read
  statuses: read
      
jobs:
  CompileBinaries:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Compile aarch64-apple-darwin
        run: TARGET=aarch64-apple-darwin deno task compile
      - name: Compile x86_64-apple-darwin
        run: TARGET=x86_64-apple-darwin deno task compile
      - name: Compile x86_64-unknown-linux-gnu
        run: TARGET=x86_64-unknown-linux-gnu deno task compile
      - name: Compile aarch64-unknown-linux-gnu
        run: TARGET=aarch64-unknown-linux-gnu deno task compile
      - name: Compile x86_64-pc-windows-msvc
        run: TARGET=x86_64-pc-windows-msvc deno task compile

  
      - name: Upload release binaries
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./gomi-*"]'
          
