name: Build Gomi

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      - name: Compile aarch64-apple-darwin
        run: TARGET=aarch64-apple-darwin deno task compile
      - name: Compile x86_64-apple-darwin
        run: TARGET=x86_64-apple-darwin deno task compile
      - name: Compile x86_64-unknown-linux-gnu
        run: TARGET=x86_64-unknown-linux-gnu deno task compile
      - name: Compile aarch64-unknown-linux-gnu
        run: TARGET=aarch64-unknown-linux-gnu deno task compile
      - name: Compile x86_64-pc-windows-msvc
        run: TARGET=x86_64-pc-windows-msvc deno task compile
  
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: gomi*
          path: ./gomi*
          if-no-files-found: error
          retention-days: 1
          
